module WordSearchPuzzle
  class Cell
    @count: untyped

    @data: untyped

    attr_reader data: untyped

    attr_reader count: untyped

    def initialize: () -> void

    def empty?: () -> untyped

    def gap?: () -> untyped

    def gap!: () -> untyped

    def in_use?: () -> untyped

    def push: (untyped data) -> untyped

    def pop: () -> untyped
  end
end
